### ISSUE TITLE
Can we add a setting to remove fog in the configuration in the future

### ISSUE THREAD

**Issue by 1450143535** [Rumi727/Fix-Camera-Resolution#1]
First of all, thank you very much for updating the graphics of Lethal Company with the high-definition graphics module by the author Sligili. I am very pleased, but may I also ask if it is possible to consider adding a defogging setting in the settings for future updates, just like the previous high-definition graphics module by the author? It is understood that there are many problems with defogging modules on the market, such as outdated versions that are not compatible with new versions. Please consider this suggestion

**Comment by Rumi727** [comment]
I think the Lethal Company rendering uses HDRP, but I've never used HDRP, so I'm not sure if it can be updated.
I'll give it a try.

**Comment by 1450143535** [comment]
May I give you a suggestion? You can try contacting the original author of high-definition graphics, Sligili, and ask if he can provide you with some ideas and suggestions for updating the dehazing module in the future

**Comment by Rumi727** [comment]
Oh, I don't think that's necessary. I searched on Google and it came up easily.
I will update to 1.1.0 soon

**Comment by Rumi727** [comment]
I just released 1.1.0 which adds a setting to remove fog.

However, you can't customize the graphics step by step like Sligili's HDLethalCompany (it's possible, but I don't think it's necessary).
Also... the HDLethalCompany mod only reduces the fog to almost invisible, but doesn't remove it, whereas the one I just added completely removes the fog, so it might be a little different. (It might look unnatural)

If it doesn't show up, wait a few hours and it will show up.

**Comment by 1450143535** [comment]
Yes, I tried your new version of defogging today, and it did make the overall look unnatural. At the same time, I also found that when I set defogging to true, it makes the overall field of view brightness very dim, which greatly affects the gaming experience. Would it be possible to make slight adjustments or, like Sligili's defogging, only reduce the fog to almost invisible, so as to improve the field of view brightness to a certain extent and achieve defogging effect
